import utils from '../../helpers/utils';
import staffOverview from './staffOverview';

const printOverviewDashboard = () => {
  let domString = '';
  domString += '<div class="container-fluid mt-5">';
  domString += '  <div class="row my-4">';
  domString += '    <div class="col-md-6 my-2">';
  domString += '      <div class="card bg-info">';
  domString += '        <div class="card-header"><h2>Staff Overview</h2></div>';
  domString += '        <div class="card-body dash-card"><div class="d-flex flex-row justify-content-around">';
  domString += staffOverview.buildStaffOverview();
  domString += '        </div></div>';
  domString += '      </div>';
  domString += '    </div>';
  domString += '    <div class="col-md-6 my-2">';
  domString += '      <div class="card bg-info">';
  domString += '        <div class="card-header"><h2>Dinos Overview</h2></div>';
  domString += '        <div class="card-body dash-card" id="dinos-overview-container"></div>';
  domString += '      </div>';
  domString += '    </div>';
  domString += '  </div>';
  domString += '  <div class="row my-4">';
  domString += '    <div class="col-md-4 my-2">';
  domString += '      <div class="card bg-info">';
  domString += '        <div class="card-header"><h2>Rides Overview</h2></div>';
  domString += '        <div class="card-body dash-card" id="rides-overview-container"></div>';
  domString += '      </div>';
  domString += '    </div>';
  domString += '    <div class="col-md-4 my-2">';
  domString += '      <div class="card bg-info">';
  domString += '        <div class="card-header"><h2>Equipment Overview</h2></div>';
  domString += '        <div class="card-body dash-card" id="equipment-overview-container"></div>';
  domString += '      </div>';
  domString += '    </div>';
  domString += '    <div class="col-md-4 my-2">';
  domString += '      <div class="card bg-info">';
  domString += '        <div class="card-header"><h2>Vendors Overview</h2></div>';
  domString += '        <div class="card-body dash-card" id="vendors-overview-container"></div>';
  domString += '      </div>';
  domString += '    </div>';
  domString += '    <div class="col-md-12 my-2">';
  domString += '      <div class="card bg-info">';
  domString += '        <div class="card-header"><h2>Chaos Monkey History</h2></div>';
  domString += '        <div class="card-body dash-card" id="chaos-overview-container"></div>';
  domString += '      </div>';
  domString += '    </div>';
  domString += '  </div>';
  domString += '</div>';
  utils.printToDom('overview-dashboard', domString);
};

export default { printOverviewDashboard };
